# Numpy Assignment Practical Questions

In [3]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [2]:
import numpy as np

### Ques1)Create a 3x3 NumPy array with random integers between 1 and 100. Then, interchange its rows and columns.

In [2]:
arr = np.random.randint(1,101,(3,3))
arr

array([[17, 60,  1],
       [88, 95, 34],
       [85, 12, 74]], dtype=int32)

In [3]:
arr.T # aray after interchanging its rows and columns (ANS)

array([[17, 88, 85],
       [60, 95, 12],
       [ 1, 34, 74]], dtype=int32)

### Ques2) Generate a 1D NumPy array with 10 elements. Reshape it into a 2x5 array, then into a 5x2 array.

In [4]:
arr1 = np.array([1,2,3,4,5,6,7,8,9,10])
arr1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [5]:
# reshaping the array in 2X 5 array using reshape method
arr1.reshape(2,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [6]:
# then reshaping it in 5 X 2 array 
arr1.reshape(5,2)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

### Ques3)  Create a 4x4 NumPy array with random float values. Add a border of zeros around it, resulting in a 6x6 array

In [7]:
arr1 = np.random.rand(4,4)

In [8]:
arr1

array([[0.58861243, 0.36968796, 0.32521349, 0.93913088],
       [0.36020571, 0.85231695, 0.65054742, 0.30237321],
       [0.95795162, 0.11905441, 0.5507076 , 0.84440975],
       [0.78859406, 0.13751874, 0.25816096, 0.40912314]])

In [16]:
arr2 = np.zeros((6,6))
arr2

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [17]:
arr2[:4,:4] = arr1 # here  we are using slicing to update the array from o-4 row and 0-4 col to fill the values of arr1

In [18]:
arr2 # final ans

array([[0.58861243, 0.36968796, 0.32521349, 0.93913088, 0.        ,
        0.        ],
       [0.36020571, 0.85231695, 0.65054742, 0.30237321, 0.        ,
        0.        ],
       [0.95795162, 0.11905441, 0.5507076 , 0.84440975, 0.        ,
        0.        ],
       [0.78859406, 0.13751874, 0.25816096, 0.40912314, 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        ]])

### Ques4) Using NumPy, create an array of integers from 10 to 60 with a step of 5.

In [19]:
# here we will use arange function to do the same 
arr = np.arange(10,61,5)
arr

array([10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60])

### Ques5) Create a NumPy array of strings ['python', 'numpy', 'pandas']. Apply different case transformations(uppercase, lowercase, title case, etc.) to each element.

In [20]:
arr = np.array(['python','numpy','pandas'])
arr

array(['python', 'numpy', 'pandas'], dtype='<U6')

In [23]:
# Uppercase transformation:
np.char.upper(arr)

array(['PYTHON', 'NUMPY', 'PANDAS'], dtype='<U6')

In [24]:
# Lowercase transformation:
np.char.lower(arr)

array(['python', 'numpy', 'pandas'], dtype='<U6')

In [27]:
# Titlecase Transformation:
np.char.title(arr)

array(['Python', 'Numpy', 'Pandas'], dtype='<U6')

In [28]:
# another option 
np.char.capitalize(arr)

array(['Python', 'Numpy', 'Pandas'], dtype='<U6')

### Ques6)  Generate a NumPy array of words. Insert a space between each character of every word in the array.

In [30]:
# we will add space to every character using np.char.join() function
arr = np.array(['My','name','is','Priyanshu','Saha'])
arr

array(['My', 'name', 'is', 'Priyanshu', 'Saha'], dtype='<U9')

In [31]:
# now adding space to every character
arr = np.char.join(' ',arr) # here we joining each character by adding space to it.

In [32]:
arr

array(['M y', 'n a m e', 'i s', 'P r i y a n s h u', 'S a h a'],
      dtype='<U17')

### Ques7) Create two 2D NumPy arrays and perform element-wise addition, subtraction, multiplication, and division.

In [33]:
# element wise addition 
first_array = np.array([1, 3, 5, 7])
second_array = np.array([2, 4, 6, 8])

# using the + operator
result1 = first_array + second_array
print("Using the + operator:",result1) 

Using the + operator: [ 3  7 11 15]


In [34]:
# element wise subtraction:
# using the - operator
result1 = first_array - second_array
print("Using the - operator:",result1)

Using the - operator: [-1 -1 -1 -1]


In [35]:
# element wise multiplication:
# using the * operator
result1 = first_array * second_array
print("Using the * operator:",result1) 

Using the * operator: [ 2 12 30 56]


In [36]:
# element wise division
# using the / operator
result1 = first_array / second_array
print("Using the / operator:",result1) 

Using the / operator: [0.5        0.75       0.83333333 0.875     ]


### Ques8) Use NumPy to create a 5x5 identity matrix, then extract its diagonal elements.

In [37]:
arr = np.eye(5)
arr

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [38]:
diagonal_elements = np.diagonal(arr) #extracting the diagonal elements 
diagonal_elements

array([1., 1., 1., 1., 1.])

### Ques 9) Generate a NumPy array of 100 random integers between 0 and 1000. Find and display all prime numbers in this array.

In [3]:
arr = np.random.randint(0,10001,(100,1))
arr

array([[8937],
       [  51],
       [5643],
       [4014],
       [5920],
       [5123],
       [1248],
       [5593],
       [1340],
       [9129],
       [   9],
       [5865],
       [5345],
       [3433],
       [8541],
       [1911],
       [3794],
       [1386],
       [2625],
       [9048],
       [8458],
       [4423],
       [3651],
       [4935],
       [4063],
       [6561],
       [4514],
       [ 709],
       [1181],
       [4969],
       [3857],
       [7354],
       [6549],
       [2790],
       [4371],
       [7648],
       [5470],
       [9940],
       [5738],
       [4734],
       [4366],
       [8356],
       [7400],
       [9943],
       [5304],
       [7308],
       [3121],
       [2053],
       [7456],
       [5343],
       [5887],
       [4129],
       [3064],
       [6492],
       [6083],
       [4834],
       [ 244],
       [8021],
       [8083],
       [2110],
       [7555],
       [6736],
       [5885],
       [8630],
       [2265],
       [4263],
       [99

In [4]:
def prime(n):
    if n<=1:
        return False
    for i in range(2,int(n/2)+1):
        if n%i == 0:
            return False
    return True
prime_vec = np.vectorize(prime) # vectorize generator object which we can apply to any particular array to find out exactly which elements are
# its prime or not
prime_vec

In [5]:
prime_array = arr[prime_vec(arr)]
prime_array # this is the final required array

array([3433, 4423,  709, 1181, 4969, 3121, 2053, 4129, 4523, 6427, 6199,
       5387, 3271], dtype=int32)

### Ques10) Create a NumPy array representing daily temperatures for a month. Calculate and display the weekly averages.

In [8]:

# Create a NumPy array with random temperatures for 30 days
temperatures = np.random.randint(60, 90, 28)

# Reshape the array into a 7x4 matrix, where each row represents a week
weekly_temps = temperatures.reshape(7,4)

# Calculate weekly averages
weekly_averages = np.mean(weekly_temps, axis=1)

# Display the weekly averages
print("Weekly Averages:")
for i, avg in enumerate(weekly_averages):
    print(f"Week {i+1}: {avg:.2f}")

Weekly Averages:
Week 1: 79.25
Week 2: 75.50
Week 3: 66.75
Week 4: 76.75
Week 5: 72.00
Week 6: 74.00
Week 7: 73.00
